package com.didi.hummer.meta;

import android.text.TextUtils;

/**
 * Created by Xingjm on 2022-01-19.
 * Save the JsCode of Component is generated by Hummer
 */
public class ComponentJsCodeInfo {
    private String script;
    private String scriptId;
    public void set(String script, String scriptId) {
        this.script = script;
        this.scriptId = scriptId;
    }
    public String getScript() {
        return this.script;
    }
    public String getScriptId() {
        return this.scriptId;
    }
    public boolean isEmpty() {
        if (TextUtils.isEmpty(this.script) || TextUtils.isEmpty(this.scriptId)) {
            return true;
        }
        return false;
    }
}
